//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuDeploy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstallationLogicProvider {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallationLogicProvider() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuDeploy.Core.Resources.InstallationLogicProvider", typeof(InstallationLogicProvider).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installation of the package &quot;{0}&quot; in version &quot;{1}&quot; is not required because the currently installed version &quot;{2}&quot; is newer..
        /// </summary>
        internal static string InstallationIsNotRequiredMessageTemplate {
            get {
                return ResourceManager.GetString("InstallationIsNotRequiredMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installation of the package &quot;{0}&quot; in version &quot;{1}&quot; is required because the currently installed version &quot;{2}&quot; is older..
        /// </summary>
        internal static string InstallationIsRequiredMessageTemplate {
            get {
                return ResourceManager.GetString("InstallationIsRequiredMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installation of the package &quot;{0}&quot; in version &quot;{1}&quot; is required. The package is currently not installed..
        /// </summary>
        internal static string InstallationIsRequiredPackageIsNotInstalledMessageTemplate {
            get {
                return ResourceManager.GetString("InstallationIsRequiredPackageIsNotInstalledMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation of the package &quot;{0}&quot; in version &quot;{1}&quot; is required. The force option has been set..
        /// </summary>
        internal static string InstallIsRequiredForceSwitchIsSetMessageTemplate {
            get {
                return ResourceManager.GetString("InstallIsRequiredForceSwitchIsSetMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninstall of package &quot;{0}&quot; is not necessary because the deployment is executed in the update-mode..
        /// </summary>
        internal static string UninstallIsNotRequiredDeploymentTypeIsUpdateMessageTemplate {
            get {
                return ResourceManager.GetString("UninstallIsNotRequiredDeploymentTypeIsUpdateMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninstall of package &quot;{0}&quot; is not necessary. The currently installed package is newer than the one you are trying to install (Installed Version: {1}, Package Version: {2})..
        /// </summary>
        internal static string UninstallIsNotRequiredMessageTemplate {
            get {
                return ResourceManager.GetString("UninstallIsNotRequiredMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninstall of package &quot;{0}&quot; is not necessary because the package is currently not installed..
        /// </summary>
        internal static string UninstallIsNotRequiredPackageIsNotInstalledMessageTemplate {
            get {
                return ResourceManager.GetString("UninstallIsNotRequiredPackageIsNotInstalledMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninstall of package &quot;{0}&quot; is necessary. The force option has been set..
        /// </summary>
        internal static string UninstallIsRequiredForceSwitchIsSetMessageTemplate {
            get {
                return ResourceManager.GetString("UninstallIsRequiredForceSwitchIsSetMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uninstall of package &quot;{0}&quot; is necessary. The new package version &quot;{1}&quot; is newer than the currently installed version &quot;{2}&quot;..
        /// </summary>
        internal static string UninstallIsRequiredNewPackageVersionIsGreaterThanCurrentVersionMessageTemplate {
            get {
                return ResourceManager.GetString("UninstallIsRequiredNewPackageVersionIsGreaterThanCurrentVersionMessageTemplate", resourceCulture);
            }
        }
    }
}
