//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuDeploy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackagingService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackagingService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuDeploy.Core.Resources.PackagingService", typeof(PackagingService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed because the base folder &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ErrorBaseFolderDoesNotExistMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorBaseFolderDoesNotExistMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed because the stream of the NuSpec file &quot;{0}&quot; cannot not be read..
        /// </summary>
        internal static string ErrorNuspecFileCannotBeReadMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorNuspecFileCannotBeReadMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed because the no NuSpec file with the file extension &quot;{0}&quot; has been found in the base folder &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorNuspecFileNotFoundMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorNuspecFileNotFoundMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed because the target package &quot;{0}&quot; cannot be opened for writing..
        /// </summary>
        internal static string ErrorOutputStreamCouldNotBeOpenedMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorOutputStreamCouldNotBeOpenedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed because the target folder &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string ErrorPackagingFolderDoesNotExistMessageTemplate {
            get {
                return ResourceManager.GetString("ErrorPackagingFolderDoesNotExistMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaing failed. Error details: {0}.
        /// </summary>
        internal static string FailedMessageTemplate {
            get {
                return ResourceManager.GetString("FailedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging the folder &quot;{0}&quot; succeeded. The NuGet package has been saved to this location: {1}.
        /// </summary>
        internal static string SuccessMessageTemplate {
            get {
                return ResourceManager.GetString("SuccessMessageTemplate", resourceCulture);
            }
        }
    }
}
