//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuDeploy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RepositorySourceConfigurationCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RepositorySourceConfigurationCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuDeploy.Core.Resources.RepositorySourceConfigurationCommand", typeof(RepositorySourceConfigurationCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a repository to the source repository configuration (using named arguments)..
        /// </summary>
        internal static string AddCommandExampleDescriptionNamedArguments {
            get {
                return ResourceManager.GetString("AddCommandExampleDescriptionNamedArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a repository to the source repository configuration (using positional arguments)..
        /// </summary>
        internal static string AddCommandExampleDescriptionPositionalArguments {
            get {
                return ResourceManager.GetString("AddCommandExampleDescriptionPositionalArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; command requires {1} parameters. The repository name and the url..
        /// </summary>
        internal static string AddCommandInvalidArgumentCountMessageTemplate {
            get {
                return ResourceManager.GetString("AddCommandInvalidArgumentCountMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action to perform ({0})..
        /// </summary>
        internal static string ArgumentDescriptionRepositoryActionTemplate {
            get {
                return ResourceManager.GetString("ArgumentDescriptionRepositoryActionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the repository (e.g. &quot;Nuget Gallery&quot;).
        /// </summary>
        internal static string ArgumentDescriptionRepositoryName {
            get {
                return ResourceManager.GetString("ArgumentDescriptionRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository url (e.g &quot;https://nuget.org/api/v2/&quot;)..
        /// </summary>
        internal static string ArgumentDescriptionRepositoryUrl {
            get {
                return ResourceManager.GetString("ArgumentDescriptionRepositoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, remove or reset the repository source configuration..
        /// </summary>
        internal static string CommandDescriptionText {
            get {
                return ResourceManager.GetString("CommandDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the specified repository configuration (using positional arguments)..
        /// </summary>
        internal static string DeleteCommandExampleDescriptionPositionalArguments {
            get {
                return ResourceManager.GetString("DeleteCommandExampleDescriptionPositionalArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use one of these actions: {0}..
        /// </summary>
        internal static string InvalidActionNameMessageTemplate {
            get {
                return ResourceManager.GetString("InvalidActionNameMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not a valid repository URL..
        /// </summary>
        internal static string InvalidRespositoryUrlMessageTemplate {
            get {
                return ResourceManager.GetString("InvalidRespositoryUrlMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all source repository configurations..
        /// </summary>
        internal static string ListCommandExampleDescription {
            get {
                return ResourceManager.GetString("ListCommandExampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the the source repository configuration to the default..
        /// </summary>
        internal static string ResetCommandExampleDescription {
            get {
                return ResourceManager.GetString("ResetCommandExampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Repository.
        /// </summary>
        internal static string SampleRepositoryName {
            get {
                return ResourceManager.GetString("SampleRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SourceRepositoryConfigurationTableHeadlineColumn1 {
            get {
                return ResourceManager.GetString("SourceRepositoryConfigurationTableHeadlineColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string SourceRepositoryConfigurationTableHeadlineColumn2 {
            get {
                return ResourceManager.GetString("SourceRepositoryConfigurationTableHeadlineColumn2", resourceCulture);
            }
        }
    }
}
