//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuDeploy.CommandLine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageSolutionCommand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageSolutionCommand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuDeploy.CommandLine.Resources.PackageSolutionCommand", typeof(PackageSolutionCommand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the build configuration to use (e.g. Debug, Release)..
        /// </summary>
        internal static string ArgumentDescriptionBuildConfiguration {
            get {
                return ResourceManager.GetString("ArgumentDescriptionBuildConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The properties to pass to MS Build (e.g. IsAutoBuild=True)..
        /// </summary>
        internal static string ArgumentDescriptionMSBuildProperties {
            get {
                return ResourceManager.GetString("ArgumentDescriptionMSBuildProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you specify this parameter the package will be published using the supplied publish configuration..
        /// </summary>
        internal static string ArgumentDescriptionPublishingConfiguration {
            get {
                return ResourceManager.GetString("ArgumentDescriptionPublishingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the solution to package (e.g. C:\dev\projects\sample\sample.sln)..
        /// </summary>
        internal static string ArgumentDescriptionSolutionPath {
            get {
                return ResourceManager.GetString("ArgumentDescriptionSolutionPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a build configuration (e.g. Debug, Release)..
        /// </summary>
        internal static string BuildConfigurationArgumentNotSetMessage {
            get {
                return ResourceManager.GetString("BuildConfigurationArgumentNotSetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a nuget package from the given solution (and pushes it to the specified nuget repository)..
        /// </summary>
        internal static string CommandDescriptionText {
            get {
                return ResourceManager.GetString("CommandDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a nuget deployment package from the solution &quot;C:\dev\projects\sample\sample.sln&quot; using the &quot;Release&quot; build configuration with the MS Build parameter &quot;IsAutoBuild=True&quot;..
        /// </summary>
        internal static string CommandExampleDescription1 {
            get {
                return ResourceManager.GetString("CommandExampleDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging failed..
        /// </summary>
        internal static string PackagingFailureMessage {
            get {
                return ResourceManager.GetString("PackagingFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging succeeded..
        /// </summary>
        internal static string PackagingSuccessMessage {
            get {
                return ResourceManager.GetString("PackagingSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing failed (Package: {0}, Publish Configuration: {1})..
        /// </summary>
        internal static string PublishingFailedMessageTemplate {
            get {
                return ResourceManager.GetString("PublishingFailedMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing succeeded (Package: {0}, Publish Configuration: {1})..
        /// </summary>
        internal static string PublishingSucceededMessageTemplate {
            get {
                return ResourceManager.GetString("PublishingSucceededMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specifiy a solution path..
        /// </summary>
        internal static string SolutionPathArgumentNotSetMessage {
            get {
                return ResourceManager.GetString("SolutionPathArgumentNotSetMessage", resourceCulture);
            }
        }
    }
}
